### ISSUE TITLE
typo re PERL_MM_USE_DEFAULT?

### ISSUE THREAD

**Issue by karenetheridge** [Perl-Toolchain-Gang/Module-Build#59]
https://github.com/Perl-Toolchain-Gang/Module-Build/blob/master/lib/Module/Build/API.pod references `PERL_MM_USE_DEFAULT` a few times - shouldn't this be `PERL_MB_USE_DEFAULT`?

**Comment by haarg** [comment]
`PERL_MM_USER_DEFAULT` is the variable it uses.
https://github.com/Perl-Toolchain-Gang/Module-Build/blob/master/lib/Module/Build/Base.pm#L553

**Comment by Leont** [comment]
There is no value in adding an additional environmental variable when it would use exactly the same semantics. PERL_MB_OPT makes sense because Build.PL argument parsing is completely different from Makefile.PL argument parsing, so that's why it makes sense there.
