### ISSUE TITLE
Issue around PERL_UNSAFE_INC / dot_in_inc

### ISSUE THREAD

**Issue by gregoa** [Perl-Toolchain-Gang/Module-Build#77]
0.42_23 added support for "dot-in-inc" in commit 5d94d41.
When I packaged 0.4224 for Debian, I therefore dropped our patch (the one mentioned in #69). The result is a build failure in libcatmandu-sru-perl. See the details and discussion in https://bugs.debian.org/865563 .

Our last thought was if the logic in the construction of the $dot_in_inc_code might be reversed, i.e:
```
--- /usr/share/perl5/Module/Build/Base.pm~    2017-06-19 17:25:18.000000000 +0000
+++ /usr/share/perl5/Module/Build/Base.pm     2017-06-23 17:42:01.820466942 +0000
@@ -1824,7 +1824,7 @@
   my $shebang = $self->_startperl;
   my $magic_number = $self->magic_number;

-my $dot_in_inc_code = $INC[-1] eq '.' ? <<'END' : '';
+my $dot_in_inc_code = $INC[-1] ne '.' ? <<'END' : '';
     if ($INC[-1] ne '.') {
         push @INC, '.';
     }

```

With this change in Base.pm, libcatmandu-sru-perl finds its test files again.

Thanks in advance for looking into this issue!

Cheers,
gregor, Debian Perl Team

**Comment by jmdh** [comment]
FTR, our discovering this was caused by a bug in a related packaging helper, cdbs. That's now been fixed and the issue is no longer visible. I defer to others about how to proceed in Module::Build as I'm unsure what the intent of the current fix, or the real need, is.

**Comment by Leont** [comment]
> Our last thought was if the logic in the construction of the $dot_in_inc_code might be reversed, i.e:

That logic is to handle `PERL_USE_UNSAFE_INC` being set during configuration but not during later stages. The most common cause of this is `sudo Build install`. AFAIK it looks like it's supposed to look.

**Comment by gregoa** [comment]
Ah, ok, now I see what the idea is; thanks.
So I guess we can close this issue.
