### ISSUE TITLE
How to not install manpages a la EU::MM's INSTALLMAN3DIR=none?

### ISSUE THREAD

**Issue by zakame** [Perl-Toolchain-Gang/Module-Build#83]
I'm trying to trim down a darkpan install of modules, and on ExtUtils::MakeMaker, I can specify

```sh
export PERL_MM_OPT="INSTALL_BASE=/path/to/darkpan INSTALLMAN1DIR=none INSTALLMAN3DIR=none"
```

to prevent installing manpages.  Is there a similar thing for Module::Build (and by extension, Module::Build::Tiny?)

I was looking into using `--install_path bindoc=none --install_path libdoc=none`, but it doesn't seem to work...

**Comment by Grinnz** [comment]
cpanm does it by adding `--config installman1dir= --config installsiteman1dir= --config installman3dir= --config installsiteman3dir=` to PERL_MB_OPT. https://github.com/miyagawa/cpanminus/blob/05c0b884fe235115fb6f1b4a0a5b53e976f7af50/Menlo-Legacy/lib/Menlo/CLI/Compat.pm#L1024

**Comment by zakame** [comment]
Thanks!  I noted that also in https://metacpan.org/pod/Module::Build#INSTALL-PATHS but forgot about `--config`.

Is this worth something to document at in say https://metacpan.org/pod/Module::Build::Cookbook ?

**Comment by Leont** [comment]
`--install_path bindoc= --install_path libdoc=` should do the trick on both `Module::Build` and `Module::Build::Tiny`

**Comment by zakame** [comment]
Great, thanks!  I'll just close this one then :+1:
