### ISSUE TITLE
Module::Build should add itself to prereqs

### ISSUE THREAD

**Issue by mtelka** [Perl-Toolchain-Gang/Module-Build#91]
MakeMaker adds this automatically to metadata (`META.json`):
```
   "prereqs" : {
      "configure" : {
         "requires" : {
            "ExtUtils::MakeMaker" : "0"
         }
      },
...
```
but `Module::Build` does not do something similar.

I believe `Module::Build` should add itself as a configure requires to `META.json` to make sure the `Module::Build` module is installed even before `perl Build.PL` is executed.

**Comment by Leont** [comment]
I am not sure why you think it doesn't? It does add itself to the configure requirements, and has done so for a long time.

**Comment by mtelka** [comment]
Because of this:
```
$ wget https://cpan.metacpan.org/authors/id/J/JT/JTBRAUN/Parse-RecDescent-1.967015.tar.gz
$ tar xf Parse-RecDescent-1.967015.tar.gz
$ cd Parse-RecDescent-1.967015
$ sed -i -e '/BUILD_REQUIRES/,+5d' Makefile.PL
$ /usr/bin/perl Makefile.PL
Checking if your kit is complete...
Looks good
Generating a Unix-style Makefile
Writing Makefile for Parse::RecDescent
Writing MYMETA.yml and MYMETA.json
$ grep -C1 MakeMaker MYMETA.json 
   "dynamic_config" : 0,
   "generated_by" : "ExtUtils::MakeMaker version 7.24, CPAN::Meta::Converter version 2.143240, CPAN::Meta::Converter version 2.150010",
   "license" : [
--
         "requires" : {
            "ExtUtils::MakeMaker" : "0"
         }
--
         "requires" : {
            "ExtUtils::MakeMaker" : "0"
         }
$ /usr/bin/perl Build.PL 
Created MYMETA.yml and MYMETA.json
Creating new 'Build' script for 'Parse-RecDescent' version '1.967015'
$ grep -C1 Module MYMETA.json 
   "dynamic_config" : 0,
   "generated_by" : "Module::Build version 0.4234",
   "license" : [
$
```

**Comment by mtelka** [comment]
Another example:
```
$ wget https://cpan.metacpan.org/authors/id/T/TH/THOR/Net-LibIDN2-1.02.tar.gz
$ tar xf Net-LibIDN2-1.02.tar.gz
$ cd Net-LibIDN2-1.02
$ /usr/bin/perl Build.PL --extra_compiler_flags=-I/usr/include/idn2 --installdirs=vendor
# Compiler seems to be /usr/gcc/10/bin/gcc
# /usr/gcc/10/bin/gcc -m64 -D_REENTRANT -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -m64 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2 -DPERL_USE_SAFE_PUTENV -fstack-protector-strong -m64 assertlibOYq3A1Pz.c -I/usr/include/idn2 -o assertlibu9XEeE6F
# /usr/gcc/10/bin/gcc -m64 -D_REENTRANT -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -m64 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2 -DPERL_USE_SAFE_PUTENV -fstack-protector-strong -m64 assertlibF8LGCz6h.c -o assertlibuW5zhDtw -I/usr/include/idn2 -lidn2
Created MYMETA.yml and MYMETA.json
Creating new 'Build' script for 'Net-LibIDN2' version '1.02'
$ diff -u META.json MYMETA.json 
--- META.json   2022-10-29 23:58:27.000000000 +0200
+++ MYMETA.json 2023-07-14 09:25:16.732253011 +0200
@@ -3,8 +3,8 @@
    "author" : [
       "Thomas Jacob <gnuthor@gmail.com>"
    ],
-   "dynamic_config" : 1,
-   "generated_by" : "Module::Build version 0.4231",
+   "dynamic_config" : 0,
+   "generated_by" : "Module::Build version 0.4234",
    "license" : [
       "perl_5"
    ],
@@ -16,16 +16,11 @@
    "prereqs" : {
       "build" : {
          "requires" : {
-            "ExtUtils::CBuilder" : "0",
-            "ExtUtils::ParseXS" : "0",
+            "ExtUtils::CBuilder" : 0,
+            "ExtUtils::ParseXS" : 0,
             "Test::More" : "0.10"
          }
       },
-      "configure" : {
-         "requires" : {
-            "Module::Build" : "0.42"
-         }
-      },
       "runtime" : {
          "requires" : {
             "perl" : "v5.6.1"
@@ -52,5 +47,5 @@
       }
    },
    "version" : "1.02",
-   "x_serialization_backend" : "JSON::PP version 4.06"
+   "x_serialization_backend" : "JSON::PP version 4.07"
 }
$
```

**Comment by Leont** [comment]
> Another example:

Your example is showing it is present in `META.json`, as it should be.

**Comment by mtelka** [comment]
The `META.json` is from downloaded package.  It is unclear how exactly the file was created.  When I tried to generate `MYMETA.json` the `Module::Build` requirement was not included there.  This is exactly what I consider a bug.

**Comment by Leont** [comment]
> The META.json is from downloaded package. It is unclear how exactly the file was created. When I tried to generate MYMETA.json the Module::Build requirement was not included there. This is exactly what I consider a bug.

Why?

Why do you want the `MYMETA.json` anyway? What are you trying to achieve here?

Why would you consider the configure requirements missing **in the MYMETA** to be an issue anyway? What breaks if it's not there? The configure requirements are only used before the MYMETA file is even generated.

I'm trying to help you here but you're kind of resistant to actually giving useful information.

**Comment by mtelka** [comment]
I'm packaging Perl modules for OpenIndiana.  To create packages I need to get their dependencies (build time, run time and test time).  To do so I analyze `MYMETA.json`.  For example [this](https://blogs.perl.org/users/neilb/2017/04/an-introduction-to-distribution-metadata.html) suggests that `MYMETA.json` should be better for that than `META.json`.  And yes, usually `MYMETA.json` is more accurate than `META.json`.  The only issue I found so far is with `Module::Build`.

**Comment by mtelka** [comment]
> The configure requirements are only used before the MYMETA file is even generated.

Then why MakeMaker adds itself to the configure requirements in the `MYMETA.json` file?

**Comment by mtelka** [comment]
Also, my example above with `Parse-RecDescent` shows that `Module::Build` is not in the `META.json`.  Only `MakeMaker` is.  So in that case my expectation is that once I run `perl Build.PL` for `Parse-RecDescent` I get `Module::Build` in `MYMETA.json`.

**Comment by mtelka** [comment]
> I'm trying to help you here but you're kind of resistant to actually giving useful information.

I'm very sorry if you feel so.  I'm trying to answer all your questions and provide all data you ask for.

**Comment by Leont** [comment]
> For example [this](https://blogs.perl.org/users/neilb/2017/04/an-introduction-to-distribution-metadata.html) suggests that MYMETA.json should be better for that than META.json. And yes, usually MYMETA.json is more accurate than META.json. The only issue I found so far is with Module::Build.

Yeah, usually it is. Or better said if `dynamic_config` is `0` you can safely use `META`, otherwise the `Makefile.PL`/`Build.PL` may add dependencies.

I do see the argument for including it for consistency, but I'm not aware of anything that's is broken (in the literal "it doesn't work" sense) this way. Modules will install fine even if it's missing in the META.json.

> I'm packaging Perl modules for OpenIndiana. To create packages I need to get their dependencies (build time, run time and test time).

Are your packages source packages or binary packages? In the latter case you really only need the runtime dependencies, in the former case things are indeed a bit more complicated.

> Also, my example above with Parse-RecDescent shows that Module::Build is not in the META.json. Only MakeMaker is. So in that case my expectation is that once I run perl Build.PL for Parse-RecDescent I get Module::Build in MYMETA.json.

I'm not sure why you expect that. configure_requires means "please install this before running the configure", not "I've used this to configure". That said, IMO this double setup Parse-RecDescent silly and unnecessary.

**Comment by mtelka** [comment]
> > I'm packaging Perl modules for OpenIndiana. To create packages I need to get their dependencies (build time, run time and test time).
> 
> Are your packages source packages or binary packages? In the latter case you really only need the runtime dependencies, in the former case things are indeed a bit more complicated.

I'm creating binary packages.  Sure, to install (and use them) I need runtime dependencies only.  But to create a package at the build server I need build dependencies too (and to test packages I need test deps).  The only way to get deps reliably (and automatically) is either `META.json` and/or `MYMETA.json`.  So I'd welcome if either file have correct and complete build/run/test deps.

> > Also, my example above with Parse-RecDescent shows that Module::Build is not in the META.json. Only MakeMaker is. So in that case my expectation is that once I run perl Build.PL for Parse-RecDescent I get Module::Build in MYMETA.json.
> 
> I'm not sure why you expect that. configure_requires means "please install this before running the configure", not "I've used this to configure". That said, IMO this double setup Parse-RecDescent silly and unnecessary.

The packaging is not so simple process as it might look at first glance.  It usually takes several steps.  First, source tarball needs to be obtained, unpacked and analyzed to find:
- how to create the binary package (for example, should I use `perl Build.PL`, or `perl Makefile.PL`, or something else?)
- what are the build dependencies and how to satisfy them; otherwise we cannot build the package (obviously)
- similarly for runtime deps; we need to list these into the package so package manager will automatically install all runtime deps for a package once an end user tries to install the package
- similarly for test deps; we need to run tests to make sure everything works as expected

Once we do have all of the above we need to create a build recipe for build server, try to build the package, install it, test it.  During this process we do not care if we got the configure deps for `Module::Build` from `META.json` or from `MYMETA.json`.  Either way would work, if it is there.  Unfortunately, for `Parse-RecDescent` it is neither in `META.json` nor in `MYMETA.json`, so we need to add such dependency manually.  It is not a showstopper, just a bit more manual work which we would like to avoid.

Once the build recipe is complete and all build/run/test deps are properly listed there, we commit it to git and the build server builds the package for us.  Before it tries to do so it installs all deps listed in the recipe.

The above process works well for `MakeMaker`, but it does not work for `Module::Build`.

If I remove all traces of `ExtUtils::MakeMaker` from all files from `Parse-RecDescent-1.967015` (except the `use ExtUtils::MakeMaker 6.62;` line in `Makefile.PL`) and run `perl Makefile.PL` then the `ExtUtils::MakeMaker` requirement appears in `MYMETA.json`.  But `Module::Build` does not do this and I do not know how to find automatically the `Module::Build` is required to build `Parse-RecDescent`.  To see `Module::Build` in `META.json`/`MYMETA.json` I need to explicitly add it to the `Module::Build->new()` call in `Build.PL`.
