### ISSUE TITLE
Fail to install

### ISSUE THREAD

**Issue by worthmine** [Perl-Toolchain-Gang/Module-Build#92]
Module::Build may have dependency to [inc::latest](https://metacpan.org/pod/inc::latest)

In fact, I couldn't install this module with `cpanm` until installing inc::latest(I have read log with `cpanm -v`)

But according to [source](https://github.com/Perl-Toolchain-Gang/Module-Build/blob/a2ecdf98c25af7dfc7070280232513e8ccec4986/Build.PL#L105), Module::Build requires inc::latest@0.500 for 'inc_bundling_support'.

I don't know which but, it doesn't work or dismisses some dependencies.

Historically, [inc::latest was forked from Module::Build](https://metacpan.org/pod/inc::latest#DESCRIPTION) but it seems to be dependent from Module::Build now.

just a way to solve this is to type `cpanm inc::latest` before `cpanm Module::Build`, but I will note it as an issue because there is no search result `inc::latest` from issue list.

**Comment by Leont** [comment]
Can you post a log of this failing? Because it shouldn't depend on `inc::latest`

**Comment by worthmine** [comment]
I'm sorry that the log was lost because I have closed my terminal tab.
And I couldn't regenerate any logs that has same error in trying to install another perl version with plenv.
