### ISSUE TITLE
Version 0.29 missing from CPAN and GitHub Releases

### ISSUE THREAD

**Issue by turtleyacht** [Perl-Toolchain-Gang/Module-Build#93]
Hello,

I'm looking for version 0.29 of Module::Build, one of the dependencies for inc::Module::Install, which Net::SSLeay 1.49 depends on.

Proceeding with collecting packages, the dependency path so far looks like

```
HTTP::Tiny (latest, 0.088)
  Net::SSLeay 1.4.9
    use::Module::Install 1.21
      Module::Build 0.29
```

On CPAN, I only see links to versions [0.2808_05](https://metacpan.org/release/EWILHELM/Module-Build-0.2808_05/view/lib/Module/Build.pm) and [0.30](https://metacpan.org/release/KWILLIAMS/Module-Build-0.30/view/lib/Module/Build.pm).

On GitHub Releases, I checked https://github.com/Perl-Toolchain-Gang/Module-Build/tags?after=0.3602, but 0.29 is missing.

After fetching Module-Install-1.21 from CPAN, attempting install on OpenBSD 7.2:

```
$ cd Module-Install-1.21
$ perl -I$HOME/perl/lib Makefile.PL PREFIX=$HOME/perl/lib
...
Checking if your kit is complete...
Looks good
Warning: prerequisite File::Remove 1.42 not found.
Warning: prerequisite Module::Build 0.29 not found.
...
Generating a Unix-style Makefile
Writing Makefile for Module::Install
Writing MYMETA.yml and MYMETA.json
Cannot find an extension with method 'write_meta' at lib/Module/Install/Admin.pm line 189.
```

[File::Remove 1.42](https://metacpan.org/release/ADAMK/File-Remove-1.42/view/lib/File/Remove.pm) has a download link. Next, I looked for Module::Build version 0.29 but didn't find it.

I understand if it's impossible or unfeasible to provide this specific version. Just wanted to investigate this route before trying other, more intensive attempts.

Apologies if this has already been addressed, or something I should take up with parent packages above. Just wanted to see if it were possible. Understandably, it's an older package and doesn't necessarily progress the latest version of this module, so may not be worth maintainer time.

If anything, leaving a marker for future folks searching past issues as well.

Thank-you,
Chris

**Comment by haarg** [comment]
It's not really obvious what you are trying to do here.

Dependency versions are minimums, not exact versions.

**Comment by turtleyacht** [comment]
Thank-you, @haarg. I used version 0.30 instead, and `make install` ran to completion.

Could there be a circular dependency between inc::Module::Install and File::Remove? I have a reproducible example below:

https://builds.sr.ht/~turtleyacht/job/1129424

Even though I install inc::Module::Install despite warnings/errors, File::Remove insists on needing it--even though Module-Install depends on File::Remove.

The end goal is wanting to use https with HTTP::Tiny, but I'm stuck at setting up dependencies of dependencies.

Any other things I could try? I understand if I should instead take it up with maintainers of other packages (File::Remove, for example).

Module::ScanDeps also has a similar issue.

**Comment by karenetheridge** [comment]
Neither File::Remove nor Net::SSLeay depend on Module::Install.

**Comment by karenetheridge** [comment]
..nor does Module::ScanDeps.

**Comment by turtleyacht** [comment]
Thank-you, @karenetheridge. That got me looking at include paths more closely: revising include path to `-I$HOME/perl/lib/libdata/perl5/site_perl` made Module-Install recognize where YAML/Tiny.pm was installed. Things should go smoothly from here.
